---
- name: Recalculate configuration checksum
  stat:
    path: "{{ pcmk_config.path }}"
    get_attributes: false
    get_checksum: true
    get_mime: false
  register: after
  run_once: true

- name: Read admin epoch
  xml:
    path: "{{ pcmk_config.path }}"
    xpath: /cib
    attribute: admin_epoch
    content: attribute
  register: xml_result
  when: before.stat.checksum != after.stat.checksum
  changed_when: false
  check_mode: false
  run_once: true

- name: Increment admin epoch
  xml:
    pretty_print: "{{ pcmk_pretty_xml }}"
    path: "{{ pcmk_config.path }}"
    xpath: /cib
    attribute: admin_epoch
    value: "{{ (xml_result.matches[0].cib.admin_epoch | default(0) | int) + 1 }}"
  when: before.stat.checksum != after.stat.checksum
  check_mode: false
  run_once: true

- name: Verify cluster configuration
  command: crm_verify --verbose --xml-file={{ pcmk_config.path | quote }}
  when: before.stat.checksum != after.stat.checksum
  changed_when: false
  check_mode: false
  run_once: true

- name: Push cluster configuration
  command: cibadmin --replace --xml-file {{ pcmk_config.path | quote }}
  when: before.stat.checksum != after.stat.checksum
  run_once: true

- name: Clean up
  file:
    path: "{{ pcmk_config.path }}"
    state: absent
  check_mode: false
  changed_when: false
  run_once: true
